from __future__ import annotations
"""存储引擎统一协议。TableStore 和 LSMStore 都符合此协议。"""
from typing import Any, List, Protocol, Set, runtime_checkable


@runtime_checkable
class StoreProtocol(Protocol):
    """所有存储引擎的接口契约。扫描算子通过此协议访问数据。"""

    @property
    def schema(self) -> Any: ...

    @property
    def row_count(self) -> int: ...

    def append_row(self, row: list) -> None: ...

    def append_rows(self, rows: List[list]) -> int: ...

    def read_all_rows(self) -> List[list]: ...

    def read_rows_by_indices(self, indices: List[int]) -> List[list]: ...

    def get_chunk_count(self) -> int: ...

    def get_column_chunks(self, column_name: str) -> list: ...

    def truncate(self) -> None: ...

    def delete_rows(self, indices: Set[int]) -> int: ...

    def update_rows(self, indices: Set[int], col_idx: int,
                    new_values: dict) -> int: ...
