from __future__ import annotations
"""Token类型和Token数据类。"""
from dataclasses import dataclass
from enum import Enum


class TokenType(Enum):
    SELECT='SELECT';FROM='FROM';WHERE='WHERE'
    INSERT='INSERT';INTO='INTO';VALUES='VALUES'
    CREATE='CREATE';TABLE='TABLE';DROP='DROP'
    AND='AND';OR='OR';NOT='NOT'
    ORDER='ORDER';BY='BY';ASC='ASC';DESC='DESC'
    LIMIT='LIMIT';OFFSET='OFFSET'
    NULL='NULL';TRUE='TRUE';FALSE='FALSE'
    IF='IF';EXISTS='EXISTS';IS='IS';AS='AS'
    NULLS='NULLS';FIRST='FIRST';LAST='LAST'
    PRIMARY='PRIMARY';KEY='KEY'
    GROUP='GROUP';HAVING='HAVING';DISTINCT='DISTINCT'
    JOIN='JOIN';ON='ON';USING='USING';NATURAL='NATURAL'
    INNER='INNER';LEFT='LEFT';RIGHT='RIGHT';FULL='FULL';OUTER='OUTER';CROSS='CROSS'
    UPDATE='UPDATE';DELETE='DELETE';SET='SET'
    CASE='CASE';WHEN='WHEN';THEN='THEN';ELSE='ELSE';END='END'
    CAST='CAST';IN='IN';BETWEEN='BETWEEN';LIKE='LIKE';ESCAPE='ESCAPE'
    UNION='UNION';INTERSECT='INTERSECT';EXCEPT='EXCEPT';ALL='ALL'
    OVER='OVER';PARTITION='PARTITION';ROWS='ROWS';RANGE='RANGE'
    UNBOUNDED='UNBOUNDED';PRECEDING='PRECEDING';FOLLOWING='FOLLOWING'
    CURRENT='CURRENT';ROW='ROW'
    EXPLAIN='EXPLAIN';ALTER='ALTER';ADD='ADD';COLUMN='COLUMN';RENAME='RENAME';TO='TO'
    INDEX='INDEX';UNIQUE='UNIQUE'
    INT='INT';INTEGER='INTEGER';BIGINT='BIGINT'
    FLOAT_KW='FLOAT';DOUBLE='DOUBLE';REAL='REAL'
    BOOLEAN='BOOLEAN';BOOL='BOOL'
    VARCHAR='VARCHAR';TEXT_KW='TEXT'
    DATE_KW='DATE';TIMESTAMP='TIMESTAMP'
    INTEGER_LIT='INTEGER_LIT';FLOAT_LIT='FLOAT_LIT';STRING='STRING';IDENTIFIER='IDENTIFIER'
    PLUS='+';MINUS='-';STAR='*';SLASH='/';PERCENT='%'
    EQUAL='=';NOT_EQUAL='!=';LESS='<';GREATER='>';LESS_EQUAL='<=';GREATER_EQUAL='>='
    PIPE_PIPE='||'
    LPAREN='(';RPAREN=')';COMMA=',';DOT='.';SEMICOLON=';'
    EOF='EOF'


@dataclass
class Token:
    type: TokenType
    value: str
    line: int = 1
    col: int = 1
